let words=[],qs=[],idx=0,score=0,correct=0,combo=0,maxCombo=0,answered=false;
const $=id=>document.getElementById(id), shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
async function load(){try{let r=await fetch("data/TARGET_GAME.json");let x=await r.json();words=(Array.isArray(x)?x:(x.words||x.data||Object.values(x))).map(v=>({id:+v.id,word:String(v.word||"").trim(),meaning:String(v.meaning||"").trim(),example:String(v.example||"").trim(),example_jp:String(v.example_jp||"").trim()})).filter(v=>v.id&&v.word&&v.meaning).sort((a,b)=>a.id-b.id);let m=words.at(-1).id;$("to").value=m;$("to").max=m;$("from").max=m;$("info").textContent=`${words.length}語を読み込みました（ID 1〜${m}）`}catch(e){$("err").textContent="単語データを読み込めませんでした。"}}}
function make(pool,n,mode){return shuffle(pool).slice(0,n).map(item=>{let d=mode==="mixed"?(Math.random()<.5?"en-ja":"ja-en"):mode,c=d==="en-ja"?item.meaning:item.word,others=[...new Set(pool.filter(x=>x.id!==item.id).map(x=>d==="en-ja"?x.meaning:x.word))];return{item,d,correct:c,choices:shuffle([c,...shuffle(others).slice(0,3)])}})}
function start(){let a=+$("from").value,b=+$("to").value,n=+$("count").value,m=$("mode").value,p=words.filter(x=>x.id>=a&&x.id<=b);$("err").textContent="";if(p.length<4){$("err").textContent="4語以上ある範囲を選んでください。";return}qs=make(p,Math.min(n,p.length),m);idx=score=correct=combo=maxCombo=0;$("start").classList.add("hidden");$("result").classList.add("hidden");$("game").classList.remove("hidden");render()}
function render(){answered=false;let q=qs[idx];$("qnum").textContent=`Q ${idx+1} / ${qs.length}`;$("bar").style.width=`${idx/qs.length*100}%`;$("score").textContent=score;$("combo").textContent=`🔥 COMBO ×${combo}`;$("type").textContent=q.d==="en-ja"?"英語 → 日本語":"日本語 → 英語";$("question").textContent=q.d==="en-ja"?q.item.word:q.item.meaning;$("example").classList.add("hidden");$("feedback").textContent="";$("feedback").className="";$("next").classList.add("hidden");let c=$("choices");c.innerHTML="";q.choices.forEach(v=>{let b=document.createElement("button");b.className="choice";b.textContent=v;b.onclick=()=>answer(v,b);c.appendChild(b)})}
function answer(sel,btn){if(answered)return;answered=true;let q=qs[idx],bs=[...document.querySelectorAll(".choice")],ok=sel===q.correct;bs.forEach(b=>b.disabled=true);if(ok){correct++;combo++;maxCombo=Math.max(maxCombo,combo);let gain=Math.min(500,100+(combo-1)*25);score+=gain;btn.classList.add("correct");$("feedback").className="ok";$("feedback").textContent=`⭕ 正解！ +${gain}点`}else{combo=0;btn.classList.add("wrong");bs.find(b=>b.textContent===q.correct)?.classList.add("correct");$("feedback").className="ng";$("feedback").textContent=`❌ 不正解　正解：${q.correct}`}$("score").textContent=score;$("combo").textContent=`🔥 COMBO ×${combo}`;if(q.item.example){$("example").textContent=`例文：${q.item.example}${q.item.example_jp?" / "+q.item.example_jp:""}`;$("example").classList.remove("hidden")}$("next").textContent=idx===qs.length-1?"結果を見る":"次の問題へ";$("next").classList.remove("hidden")}
function next(){if(idx<qs.length-1){idx++;render()}else{result()}}
function result(){$("game").classList.add("hidden");$("result").classList.remove("hidden");$("finalScore").textContent=score;$("correct").textContent=correct;$("total").textContent=qs.length;$("accuracy").textContent=Math.round(correct/qs.length*100)+"%";$("maxCombo").textContent=maxCombo;let r=correct/qs.length;$("message").textContent=r===1?"🎉 パーフェクト！":r>=.8?"🔥 かなり仕上がってる！":r>=.6?"👍 いい感じ！":r>=.4?"💪 もう一回！":"📚 復習して再挑戦！"}
$("startBtn").onclick=start;$("next").onclick=next;$("again").onclick=()=>{$("result").classList.add("hidden");$("start").classList.remove("hidden")};load();